# Generated by Django 4.0.3 on 2022-03-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], max_length=20),
        ),
    ]
